version: "3.5"

services:
    zabbix-server:
        container_name: zabbix-server
        image: zabbix/zabbix-server-mysql:5.0.19-alpine
        ports:
            - "10051:10051"
        environment:
            - "DB_SERVER_HOST=zabbix-server-db"
            - "MYSQL_USER=zabbix"
            - "MYSQL_PASSWORD=zabbix"
            - "ZBX_JAVAGATEWAY_ENABLE=true"                
            - "ZBX_JAVAGATEWAY=zabbix-java-gateway"
    zabbix-proxy:
        container_name: zabbix-proxy-mysql
        image: zabbix/zabbix-proxy-mysql:5.0.19-alpine
        environment:
            - "DB_SERVER_HOST=zabbix-proxy-db"
            - "MYSQL_USER=zabbix"
            - "MYSQL_PASSWORD=zabbix"
            - "ZBX_JAVAGATEWAY_ENABLE=true"    
            - "ZBX_JAVAGATEWAY=zabbix-java-gateway"            
    zabbix-java-gateway:
        container_name: zabbix-java-gateway
        image: zabbix/zabbix-java-gateway:5.0.19-alpine
        environment:
            - "DB_SERVER_HOST=zabbix-server-db"
            - "MYSQL_USER=zabbix"
            - "MYSQL_PASSWORD=zabbix"
    zabbix-app:
        container_name: zabbix-app
        image: zabbix/zabbix-web-nginx-mysql:5.0.19-alpine
        ports:
            - "8085:8080"
        environment:
            - "DB_SERVER_HOST=zabbix-server-db"
            - "MYSQL_USER=zabbix"
            - "MYSQL_PASSWORD=zabbix"
            - "ZBX_SERVER_HOST=zabbix-server"
            - "PHP_TZ=Europe/Amsterdam"
    zabbix-agent:
        container_name: zabbix-agent
        image: zabbix/zabbix-agent:5.0.19-alpine
        environment:
            - "ZBX_HOSTNAME=Zabbix server"
            - "ZBX_SERVER_HOST=zabbix-proxy"
    webapp:
        container_name: webapp
        build: webapp
        ports: 
            - "8080:8080"
    zabbix-server-db:
        container_name: zabbix-server-db
        image: mysql:8.0.28
        command: --character-set-server=utf8 --collation-server=utf8_bin
        environment:
            - "MYSQL_USER=zabbix"
            - "MYSQL_PASSWORD=zabbix"
            - "MYSQL_ROOT_PASSWORD=zabbix"
            - "MYSQL_DATABASE=zabbix"
    zabbix-proxy-db:
        container_name: zabbix-proxy-db
        image: mysql:8.0.28
        command: --character-set-server=utf8 --collation-server=utf8_bin
        environment:
            - "MYSQL_USER=zabbix"
            - "MYSQL_PASSWORD=zabbix"
            - "MYSQL_ROOT_PASSWORD=zabbix"
            - "MYSQL_DATABASE=zabbix_proxy"            
